default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-practice-nested-resources-companies-development

test:
  <<: *default
  database: rails-practice-nested-resources-companies-test
